print("hello hi I am trying to learn git")
print("this is for 2nd comment")
print("3rd comment by dev")
print("4th comment from github")
print("5th from github")
print("6th from github/dev")
print("7th from master local")
print("8th from dev local")
